name: node build lint test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:

  build_lint_test:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
      - name: Run CI build
        run: npm run ci:build
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run fe:test # be:test only works with database :(
